// <auto-generated />
using System;
using AstraAiDotnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Astra_Ai_Dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606192950_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstraAiDotnet.ClientesPremium.Models.ClientePremium", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLIENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCliente"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CNPJ");

                    b.Property<decimal>("DemandaContratadaGwh")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("DEMANDA_CONTRATADA_GWH");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<string>("StatusCadastro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_CADASTRO");

                    b.HasKey("IdCliente")
                        .HasName("AST_CLIENTE_PREMIUM_PK");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UK_CLIENTE_CNPJ");

                    b.ToTable("AST_CLIENTE_PREMIUM", (string)null);
                });

            modelBuilder.Entity("AstraAiDotnet.Leiloes.Models.Leilao", b =>
                {
                    b.Property<long>("IdLeilao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEILAO")
                        .HasDefaultValueSql("SEQ_AST_LEILAO.NEXTVAL");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_HORA_FIM");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_HORA_INICIO");

                    b.Property<decimal>("GwhDisponivel")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("GWH_DISPONIVEL");

                    b.Property<long>("IdRectennaOrigem")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_RECTENNA_ORIGEM");

                    b.Property<long>("IdSatelite")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SATELITE");

                    b.Property<decimal>("PrecoMinPorGwh")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("PRECO_MIN_POR_GWH");

                    b.Property<string>("StatusLeilao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_LEILAO");

                    b.HasKey("IdLeilao")
                        .HasName("AST_LEILAO_BIDDING_PK");

                    b.ToTable("AST_LEILAO_BIDDING", (string)null);
                });

            modelBuilder.Entity("AstraAiDotnet.LogTransacoes.Models.LogTransacao", b =>
                {
                    b.Property<long>("IdTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TRANSACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTransacao"));

                    b.Property<DateTime>("DataFaturamento")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_FATURAMENTO");

                    b.Property<long>("IdClienteVencedor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLIENTE_VENCEDOR");

                    b.Property<long>("IdLeilao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEILAO");

                    b.Property<decimal>("TaxaAstra")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("TAXA_ASTRA");

                    b.Property<decimal>("ValorArrematado")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR_ARREMATADO");

                    b.HasKey("IdTransacao")
                        .HasName("AST_LOG_TRANSACAO_PK");

                    b.HasIndex("IdClienteVencedor");

                    b.HasIndex("IdLeilao");

                    b.ToTable("AST_LOG_TRANSACAO", (string)null);
                });

            modelBuilder.Entity("AstraAiDotnet.LogTransacoes.Models.LogTransacao", b =>
                {
                    b.HasOne("AstraAiDotnet.ClientesPremium.Models.ClientePremium", "ClienteVencedor")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdClienteVencedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AstraAiDotnet.Leiloes.Models.Leilao", "Leilao")
                        .WithMany("LogTransacoes")
                        .HasForeignKey("IdLeilao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteVencedor");

                    b.Navigation("Leilao");
                });

            modelBuilder.Entity("AstraAiDotnet.ClientesPremium.Models.ClientePremium", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("AstraAiDotnet.Leiloes.Models.Leilao", b =>
                {
                    b.Navigation("LogTransacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
